package com.example.airlinebooking.airline_booking_system.mapper;

import com.example.airlinebooking.airline_booking_system.dto.flight.FlightRequestDTO;
import com.example.airlinebooking.airline_booking_system.dto.flight.FlightResponseDTO;
import com.example.airlinebooking.airline_booking_system.entity.AirportEntity;
import com.example.airlinebooking.airline_booking_system.entity.FlightEntity;
import org.springframework.stereotype.Component;

@Component
public class FlightMapper {

    public FlightEntity toEntity(FlightRequestDTO flightRequestDTO, AirportEntity sourceAirport, AirportEntity destinationAirport) {
        return new FlightEntity(
                null,  // flightId will be generated by the database
                flightRequestDTO.getFlightNumber(),
                flightRequestDTO.getAirlineName(),
                flightRequestDTO.getDepartureTime(),
                flightRequestDTO.getArrivalTime(),
                null,  // durationMinutes is a transient field
                flightRequestDTO.getTotalSeats(),
                flightRequestDTO.getTotalSeats(),  // Initially, all seats are available
                flightRequestDTO.getPrice(),
                sourceAirport,
                destinationAirport
        );
    }

    public FlightResponseDTO toResponseDTO(FlightEntity entity) {
        return new FlightResponseDTO(
                entity.getFlightId(),
                entity.getFlightNumber(),
                entity.getAirlineName(),
                entity.getDepartureTime(),
                entity.getArrivalTime(),
                entity.getDurationMinutes(),
                entity.getTotalSeats(),
                entity.getAvailableSeats(),
                entity.getPrice(),
                entity.getSourceAirportEntity().getAirportCode(),
                entity.getDestinationAirportEntity().getAirportCode()
        );
    }
}